### ISSUE TITLE
Float Grid Support

### ISSUE THREAD

**Issue by pronkman** [ThemeAwesome/WP-Forge#54]
Hi,
I've noticed that the theme includes an option to choose between the float and flex grids but selecting float still outputs the flex grid. Has support for the float grid been removed?
Thx!

**Comment by tsquez** [comment]
hey there,

Yes basically it has with the new XY Grid. However in this new update that I will be pushing out soon, the user will be able to use either the XY, Float or Flex Grids.

**Comment by pronkman** [comment]
Great! Any idea when the new update can be expected?

**Comment by tsquez** [comment]
Can't really give a definite time frame, i have to add a bunch of code to all the files and make sure everything works the way it's supposed to... it's a monster lol

**Comment by tsquez** [comment]
I am closing this as I have removed the option to select between float and flex grids in the latest version of WP-Forge 6.5.3 which will be released here in a few minutes. Will just be going with the XY Grid in the latest version of Foundation for Sites.
